# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main   # o la rama que uses

pool:
  name: 'Default'   # cámbialo por el pool donde registraste tu agente

steps:
- script: echo "Hello World desde el agente Windows 🎉"
  displayName: 'Mensaje de prueba'

- script: dir
  displayName: 'Listar archivos en el workspace'
